databases:
  - name: books_rails_benchmark_production
    databaseName: books_rails_benchmark_production
    user: books_rails_benchmark
    plan: free

services:
  - type: web
    name: books_rails_benchmark_production
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
